export type SimpleIconName =
  | "arrow-down"
  | "arrow-up"
  | "sphere"
  | "discount-circle"
  | "empty-star"
  | "filled-star"
  | "flash-2"
  | "flash"
  | "headphone"
  | "message-question"
  | "radar"
  | "security-card"
  | "security-user"
  | "strong-box"
  | "telegram"
  | "tick-circle"
  | "ticket"
  | "vk-icon"
  | "menu"
  | "close"
  | "usd"
  | "kzt"
  | "rub";

export type IconName = SimpleIconName;
